### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by oleander** [deju/poloniex-bitbar#1]
FYI; OS X 10.6+ has support for Ruby, which is a bit less error prone then using bash.

`$ ruby -r pp -r net/http -r json -e 'pp JSON.parse(Net::HTTP.get(URI("https://poloniex.com/public\?command\=returnTicker")))'`

The shebang `/usr/bin/env ruby` can be used to access the currently installed version. Hope that helps :)

**Comment by deju** [comment]
@oleander It is awesome. Thanks
